
[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.85
blur = false

[window.padding]
x = 7
y = 10

[font]
size = 11

[font.normal]
family = "BerkeleyMono"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
