[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/ghostty"
# With `theme` set to "tinted-theming", this will be where Ghostty looks for the theme file:
hook = "command cp -f %f ~/.config/ghostty/themes/tinted-theming"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
themes-dir = "sh"
# With `theme` set to "tinted-theming", this will be where Ghostty looks for the theme file:
hook = "command cp -f %f ~/.config/fzf/themes/tinted-theming.sh"
supported-systems = ["base16", "base24"]
