[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/ghostty"
hook = "command cp -f %f ~/.config/ghostty/themes/tinted-theming"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
themes-dir = "sh"
hook = "command cp -f %f ~/.config/fzf/themes/tinted-theming.sh"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
themes-dir = "colors"
hook = "command cp -f %f ~/.config/tmux/themes/tinted-theming.conf"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/base16-waybar"
name = "tinted-waybar"
themes-dir = "colors"
hook = "command cp -f %f ~/.config/waybar/themes/tinted-theming/tinted-theming.css"
supported-systems = ["base16"]

[[items]]
path = "https://github.com/tinted-theming/base16-rofi"
name = "tinted-rofi"
themes-dir = "colors"
hook = "command cp -f %f ~/.config/rofi/themes/tinted-theming.rasi && set-waybar-theme.sh tinted-theming"
supported-systems = ["base16"]
