alias conf="cd ~/.config"
alias proj="cd ~/Projects"
alias dot="cd ~/Projects/.dotfiles"
alias note="cd ~/Projects/notes"
alias down="cd ~/Downloads"
alias pic="cd ~/Pictures"
alias wall="cd ~/Pictures/Wallpapers"
